# Generated by Django 2.2.5 on 2019-10-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Administrador", "Administrador"),
                    ("Digitador", "Digitador"),
                    ("Usuario", "Usuario"),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo de Usuario",
            ),
        ),
    ]
