# Generated by Django 2.2.5 on 2019-11-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191022_1950'),
        ('users', '0004_auto_20191031_1753'),
    ]

    operations = [
    ]
