# Generated by Django 2.2.5 on 2019-11-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_merge_20191107_1826")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Administrador", "Administrador"),
                    ("Digitador", "Digitador"),
                    ("Franquicia", "Franquicia"),
                    ("Cliente", "Cliente"),
                ],
                default="Franquicia",
                max_length=50,
                verbose_name="Tipo de Usuario",
            ),
        )
    ]
