# Generated by Django 2.2.5 on 2019-11-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pizzas", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="name",
            field=models.CharField(default="", max_length=250, verbose_name="Nombre"),
        )
    ]
