# Generated by Django 2.2.8 on 2019-12-12 05:48

from django.db import migrations, models
import pizzas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, default='images/pizza_default.png', null=True, upload_to=pizzas.models.pizza_image_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='image',
            field=models.ImageField(blank=True, default='images/topping_default.png', null=True, upload_to=pizzas.models.topping_image_path, verbose_name='Imagen'),
        ),
    ]
