# Generated by Django 2.2.5 on 2019-11-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("franchises", "0004_auto_20191031_1338"),
        ("franchises", "0004_auto_20191022_1950"),
    ]

    operations = []
