# Generated by Django 2.2.5 on 2019-11-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("franchises", "0006_franchise_theme")]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="color",
            field=models.CharField(
                choices=[
                    ("#coffee", "Café"),
                    ("dark", "Oscuro"),
                    ("dust", "Arena"),
                    ("gray", "Gris"),
                    ("lime", "Lima"),
                    ("mint", "Menta"),
                    ("navy", "Azul marino"),
                    ("ocean", "Oceano"),
                    ("prickly-pear", "Higo"),
                    ("purple", "Violeta"),
                    ("well-red", "Rojo"),
                    ("yellow", "Amarillo"),
                ],
                default="well-red",
                max_length=50,
                verbose_name="Tema",
            ),
        ),
        migrations.AlterField(
            model_name="franchise",
            name="theme",
            field=models.CharField(
                choices=[
                    ("a", "Tema A"),
                    ("b", "Tema B"),
                    ("c", "Tema C"),
                    ("d", "Tema D"),
                    ("e", "Tema E"),
                ],
                default="a",
                max_length=50,
                verbose_name="Tema",
            ),
        ),
    ]
